export const GUIDE_IDS = ["claim", "claim-number", "roster", "slot", "historical-claim", "watchlist", "privacy", "anonymous-scout", "fan-created-page", "verified-artist", "founders-board", "historical-100", "season-board", "points", "hold-14", "claim-lock", "base-point", "at-risk", "pending-page", "referral-ladder", "wait-30", "leagues"] as const;
export type GuideId = (typeof GUIDE_IDS)[number];

export const GUIDE: Record<GuideId, { title: string; short: string; body: string }> = {
  "claim": { title: "Claim", short: "Backing an artist. You get a permanent number.", body: "Claiming puts your name next to an artist you believe in, before most people have heard of them. It uses one slot on your roster and gives you a claim number that is yours for good." },
  "claim-number": { title: "Claim number", short: "The order you arrived. #7 means seventh.", body: "Numbers are handed out by the server, one at a time, so two people never get the same one. Your number never changes, even if you drop the artist later." },
  "roster": { title: "Roster", short: "The artists you are backing right now.", body: "Your roster is your active claims. Everyone starts with 5 slots, so each choice matters. Bringing friends opens more, and the steps are listed under Slot ladder." },
  "slot": { title: "Slot", short: "One place on your roster.", body: "A claim uses one slot. Dropping a claim frees the slot. You start with 5, and bringing friends can open more." },
  "historical-claim": { title: "Historical claim", short: "A claim you dropped. It keeps its number and date.", body: "Dropping an artist does not erase your claim. It moves to your history with its original number and date, and it stops earning points." },
  "watchlist": { title: "Watchlist", short: "Follow an artist without claiming. No number, no slot.", body: "Watching earns nothing and gives you no number, but you can follow their growth and decide when to claim. The public never sees who is watching." },
  "privacy": { title: "Who sees your name", short: "You choose, for each claim and each watch.", body: "For a claim you can show your name, show it to the artist only, or stay anonymous. For a watch, the artist either sees your name or does not. Your number and points are the same either way, and you can change this later." },
  "anonymous-scout": { title: "Anonymous scout", short: "Someone who chose not to show their name to the artist or on the boards. They still count and still score.", body: "Staying anonymous only changes who can see your name. The claim number is still yours, the claim still counts toward the artist, and it still earns points. You can change your choice later." },
  "fan-created-page": { title: "Fan-created page", short: "A page made by fans, not yet verified by the artist.", body: "Anyone can add an artist. The page says so until the real artist proves it is theirs." },
  "verified-artist": { title: "Verified artist", short: "The artist proved the page is theirs.", body: "The artist pastes a one-time code into the bio of one of their own public pages, and ClaimedFirst checks for it. Verified artists can add Top Songs and a donation link." },
  "founders-board": { title: "Founders board", short: "The 100 earliest claims on an artist.", body: "Active and historical claims both count, and dropped ones are labeled. A new claim shows at once, greyed as provisional with the days left until it counts. A claim dropped before day 14 stays listed and is labeled with how long it was held." },
  "historical-100": { title: "Historical 100", short: "Your 100 earliest claim numbers.", body: "It lists your best early finds, active and dropped. A new claim shows at once, greyed as provisional until it has been held for 14 days. A claim dropped before day 14 stays listed as dropped early." },
  "season-board": { title: "Season board", short: "A monthly ranking by points. Recognition only.", body: "Seasons run monthly and then reset, so new scouts always have a fair start. Your claim numbers and history never reset. There are no prizes." },
  "points": { title: "Points", short: "New fans an artist gains after your claim, with an early bonus.", body: "The earlier your claim, the bigger the bonus: 5x for the first 10, 3x up to 50, 2x up to 200, then 1x. Only claims you currently hold earn points." },
  "hold-14": { title: "Provisional claim", short: "A claim younger than 14 days. It shows greyed, with the days left until it counts.", body: "Nothing is hidden: a new claim is on the boards right away. Until it has been held for 14 days it is provisional, and if it is dropped before then it stays listed as dropped early, with no trophy value. This stops people claiming lots of artists and dropping them straight away." },
  "claim-lock": { title: "3-day claim lock", short: "A new claim cannot be dropped for 3 days.", body: "New claims are locked for 3 days so numbers stay meaningful. Your Roster shows the date and time each one can be dropped. After that you can drop it as usual." },
  "base-point": { title: "Base point", short: "Every claim earns 1 point, so you appear on the leaderboard right away.", body: "Growth points, from new fans joining an artist after your claim, start when your account is 3 days old. The leaderboard shows Total points." },
  "at-risk": { title: "At risk", short: "Points from claims under 14 days old.", body: "Dropping any claim this season removes its points, so these are the ones most likely to go. The leaderboard shows At risk next to Total points." },
  "pending-page": { title: "Pending page", short: "A page waiting for 3 scouts before it goes live.", body: "Anyone can add an artist. The page shows its name, source link and how many of the 3 scouts it has. Adding your support counts you as one. A verified artist counts as 2, so one more scout finishes the page. Claims open once it is live." },
  "referral-ladder": { title: "Slot ladder", short: "Bring friends and get more slots. The steps are public.", body: "You start with 5 slots. 2 friends open 10 slots, 5 friends open 20 slots, 10 friends open 30 slots and 20 friends open 50 slots, which is the most. A friend counts once they have joined, their account is 3 days old and they have made a claim. Your Roster shows each friend as pending or counted." },
  "wait-30": { title: "30-day wait", short: "After dropping an artist, wait 30 days to claim them again.", body: "When you come back you get a new, later number. Your old number stays in your history." },
  "leagues": { title: "Leagues", short: "When enough scouts have joined, the season board splits into leagues.", body: "Scouts with a similar amount of room on their roster compete together. Your league is set when the season starts, so it does not change mid-season." },
};
