import { readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { renderToStaticMarkup } from "react-dom/server";
import { beforeEach, expect, test, vi } from "vitest";

let user: { id: string } | null = null;
vi.mock("next/link", () => ({ default: ({ href, children }: { href: string; children: React.ReactNode }) => <a href={href}>{children}</a> }));
vi.mock("next/font/google", () => ({ Fraunces: () => ({ variable: "f" }), DM_Sans: () => ({ variable: "d" }) }));
vi.mock("@/components/SiteHeader", () => ({ default: () => <header /> }));
vi.mock("@/lib/supabase/server", () => ({ createClient: async () => ({ auth: { getUser: async () => ({ data: { user } }) } }) }));

import Home from "./page";
import RootLayout, { metadata } from "./layout";

beforeEach(() => { user = null; });

test("signed out, / is the marketing page with its headline and the three sections", async () => {
  const html = renderToStaticMarkup(await Home());
  expect(html).toContain("Find them first.<br/><em>Keep the number.</em>");
  for (const id of ["artists", "how", "fans"]) expect(html).toContain(`id="${id}"`);
  for (const h of ["Give your first listeners a place in your story.", "Three small steps. Your page is yours.", "Your taste has a timestamp."]) expect(html).toContain(h);
  for (const href of ["/login", "/discover"]) expect(html).toContain(`href="${href}"`);
  expect(html).not.toContain("https://www.claimedfirst.com");
  expect(html).toContain("Illustrative page.");
  expect(html).not.toContain('Quick links');
});

test("every Find your page link goes to the search box on Discover", async () => {
  const html = renderToStaticMarkup(await Home());
  const finds = [...html.matchAll(/<a href="([^"]*)">Find your (?:artist )?page<\/a>/g)];
  expect(finds.length).toBeGreaterThanOrEqual(3);
  for (const m of finds) expect(m[1]).toBe("/discover#search");
  expect(html).toContain('href="/discover">Discover artists');
});

test("signed out marketing copy has no banned words and no exclamation marks", async () => {
  const text = renderToStaticMarkup(await Home()).replace(/<[^>]+>/g, " ").replace(/&#x27;|&apos;/g, "'").toLowerCase();
  const banned = ["leverage", "seamless", "seamlessly", "game-changer", "unlock", "empower", "robust", "synergy", "deep dive", "revolutionize", "cutting-edge", "best-in-class", "supercharge", "effortless", "frictionless", "disrupt", "viral", "next-generation", "ecosystem", "community-driven", "web3", "gamify", "gamification", "invest", "investor", "investing", "investment", "stock", "shares", "trade", "trading", "portfolio", "return", "roi", "gains", "profit", "market", "buy in", "cash out", "bet", "wager", "odds", "rich", "to the moon"];
  for (const w of banned) expect(text, w).not.toMatch(new RegExp(`(^|[^a-z0-9])${w.replace(/[-]/g, "\\-")}([^a-z0-9]|$)`));
  expect(text).not.toContain("!");
});

test("signed in keeps the existing home with quick links", async () => {
  user = { id: "u1" };
  const html = renderToStaticMarkup(await Home());
  expect(html).toContain("<h1>ClaimedFirst</h1>");
  expect(html).toContain('aria-label="Quick links"');
  expect(html).not.toContain('id="artists"');
});

test("a signed-in scout gets a roster link and no sign-in link", async () => {
  user = { id: "u1" };
  const html = renderToStaticMarkup(await Home());
  expect(html).toContain('href="/roster"');
  expect(html).not.toContain('href="/login"');
});

test("site metadata is set and nothing says Create Next App", () => {
  expect(metadata.title).toEqual({ default: "ClaimedFirst", template: "%s · ClaimedFirst" });
  expect(metadata.description).toBe("Find AI music artists before everyone else, and keep the number.");
  const walk = (d: string): string[] => readdirSync(d).flatMap((f) => (statSync(join(d, f)).isDirectory() ? walk(join(d, f)) : [join(d, f)]));
  const bad = walk("src/app").filter((f) => !f.includes(".test.") && /Create Next App|Generated by create next app/.test(readFileSync(f, "utf8")));
  expect(bad).toEqual([]);
});

test("the footer links to Terms, Privacy and Guide", () => {
  const html = renderToStaticMarkup(<RootLayout params={Promise.resolve({})}>{null}</RootLayout>);
  expect(html).toMatch(/<footer[\s\S]*href="\/terms"[\s\S]*href="\/privacy"[\s\S]*href="\/guide"/);
});
